### ISSUE TITLE
Add monitoring and check to ide-urls

### ISSUE THREAD

**Issue by CREITZ25** [devonfw/IDEasy#126]
As a user, I want to check the repository ide-urls so that there are consistent informations.

For example, if there is a release configured, the URL files for all three environments should also be available, 
as well as the associated checksum files.

* A first PR should improve the logging and end the github action with a report summary (as described below).
* A next step could be to send out a notification from the github action if the report includes at least one error so we receive the report summary via email or MS Teams message.
* A further step could then be to build some kind of "memory" so we only get notified again if "new errors/warnings" come up (so an error for the exact same tool+edition+version or URL that occurs again in the next nightly run will not trigger another notification to avoid spam). This "memory" should not be stored in ide-urls itself - maybe we can find an easy standard solution for github-actions to persist state.

Input from https://github.com/devonfw/ide/issues/1219

Our github action [update-urls.yml](https://github.com/devonfw/ide/blob/master/.github/workflows/update-urls.yml) logs errors if downloads fail (including download verification) but continues successfully also on such errors.
We should add a mechanism to count errors in a structured way and then send a notification with an error report. If there is no error also no notification should be send. My suggestion would be to use an email notification. If we use a public distribution list and want to avoid spam, we can configure it as github secret.
To collect the errors, we we should create a structured error state object and count the errors per tool and edition. We should then also count the success so we could e.g. determine and error rate (e.g. gradle 100% error vs. gradle 1% errors). My first draft suggestion:
* «tool»/«edition»: versions added: 5 failed, 7 succeeded, 13 total, 38,4% error - versions verified: 0 failed, 0 succeeded, 0 total, 0% error

FYI: I pointed that example also to point out a potential division by zero issue before implementation :)

**Comment by hohwille** [comment]
See devonfw/ide#1219

**Comment by hohwille** [comment]
> Also we should add our a state as a badge in our README.asciidoc.

I will remove this from the story as the badge is already in our README for a long time so IMHO this point is already solved.
