### ISSUE TITLE
ProgressBar AssertionError, if content-length not set

### ISSUE THREAD

**Issue by moritzLanger** [devonfw/IDEasy#130]
### Expected behavior

If a download does not provide a content length it should still be downloaded using the workaround show [here](https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/io/FileAccessImpl.java#L104).
### Actual behavior

An assertion error will be thrown if the content length is not set and/or provided with the download. This error is throw in the IdeProgressBarTestImpl as it asserts that the total of the progress bar equals its max before closing, as can be seen [here](https://github.com/devonfw/IDEasy/blob/main/cli/src/test/java/com/devonfw/tools/ide/io/IdeProgressBarTestImpl.java#L57).

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  Mock a server, which contains/downloads a File without specifing the Content length in the header
2.  Run the InstallCommandlet with the URL from the mocked server.

### Affected version:

* OS: Windows
* OS : probably Linux/Mac aswell

**Comment by hohwille** [comment]
Consider adding a method to complete the progressbar to our own API that can complete the progressbar (setting actual to max). Or as alternative create a dummy implementation that does not use the real progressbar if no content-length is available. If possible still give feedback to user of progress (x MB / ?).
