### ISSUE TITLE
Implement PluginBasedCommandlet

### ISSUE THREAD

**Issue by alfeilex** [devonfw/IDEasy#142]
Currently, we use `IdeToolCommandlet` to handle plugin based commandlets like `eclipse`, `vscode`, `intellij`. But there are also other plugin based tools like `mvn`. This tool is not an `ide` tool and does not need functionalities like installing plugins etc. that are defined in `IdeToolCommandlet`.

This story should implement an abstract **PluginBasedCommandlet** which extends **LocalToolCommandlet.**  Functions like `getPluginsMap` or `getPluginsConfigPath` should be moved from **IdeToolCommandlet** to the new class. 

Finally, the classes should be in this relationship:
  ```
  PluginBasedToolCommandlet extends LocalToolCommandlet
        Mvn extends PluginBasedToolCommandlet
        IdeToolCommandlet extends PluginBasedToolCommandlet
            Eclipse extends IdeToolCommandlet
            ...
```

There are related issues that may be in conflict with this issue:
#93, #94

**Comment by hohwille** [comment]
Done with PR #141
