### ISSUE TITLE
Offer git restore if urls were changed locally

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#148]
As an IDEasy user, I want IDEasy to detect if I've modified my local `urls` repository.
It would be nice if IDEasy could provide a notification if `urls` is in an inconsistent state and offer an automatic `git restore`.

Currently IDEasy just checks if the `urls` folder exists and if not, it does a `git checkout`.
If the folder exists, IDEasy attempts only a `git pull` which can not detect any changes e.g. deletions.

If the user is offline and force mode is active, the user needs to be asked if he wants to repair (and lose) his local changes on the urls repository.

**Comment by hohwille** [comment]
See also #173 
We can detect conflicts if not force is active for git update and in such case ask the user (with warning to lose all changes) if he wants to revert all his changes.

**Comment by jan-vcapgemini** [comment]
Can be closed because for urls we want to enforce a git reset.
Will be continued if other processes using git reset should wait for user input.
