### ISSUE TITLE
Implement ToolCommandlet for Cobigen

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#15]
Create `ToolCommandlet` for Cobigen
Old commandlet:
https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/cobigen

**Comment by CREITZ25** [comment]
The cobigen commandlet is formed from a Maven artifact. There is currently no information about the procedure in the Java environment.

**Comment by hohwille** [comment]
> Merge first #165 The cobigen commandlet is formed from a Maven artifact. There is currently no information about the procedure in the Java environment.

CobiGen URL Updater has already been implemented so unlike in the current implementation in devonfw-ide we can use the standard download appraoch for CobiGen as well:
https://github.com/devonfw/ide-urls/tree/master/cobigen/cobigen/
