### ISSUE TITLE
Integration of software from a Maven repository

### ISSUE THREAD

**Issue by CREITZ25** [devonfw/IDEasy#165]
As a developer, I want to be able to add new software tools also from Maven repositories. For this we need the to add another implementation of `ToolRepository` as class e.g. called `MavenToolRepository`.

existing bash code for this can be found here (but should not be migrated 1:1):
* [doMavenGetLatestVersion](https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/functions#L985-L993)
* [doUpgradeMavenArtifact ](https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/functions#L1126-L1181)

As @slskiba already found out, this might have already been implemented by `MavenBasedUrlUpdater` and is in use by `CobiGen` and `Jasypt`.

**Comment by hohwille** [comment]
Already done as you can see here: https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/url/updater/MavenBasedUrlUpdater.java
