### ISSUE TITLE
Use Project folder for automatic intellij project detection

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#203]
As an intellij user, I want IDEasy to automatically detect my intellij projects located in the IDEasy projects folder structure so that I can easily update all of my ide-settings.

**Comment by hohwille** [comment]
We will not implement this. IDEasy will open IntelliJ in your workspace. You can from there have your git repo(s) inside the workspace as subfolder and only this way we can properly preconfigure maven installation, settings.xml, etc. via `.idea` folder.
