### ISSUE TITLE
Implement ToolCommandlet for Github CLI

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#21]
Create `ToolCommandlet` for Github CLI
Old commandlet:
https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/gh

**Comment by CREITZ25** [comment]
It seems it is allready done.

**Comment by hohwille** [comment]
Commandlet is indeed implemented as [Gh.java](https://github.com/devonfw/IDEasy/blob/main/cli/src/main/java/com/devonfw/tools/ide/tool/gh/Gh.java).
As the old bash commandlet does not seem to do anything more, it seems indeed to be done so I will close.
Thanks @CREITZ25 for pointing this out.
