### ISSUE TITLE
Pass to maven the m2 repo location as setting argument instead of using $MAVEN_OPTS environment variable

### ISSUE THREAD

**Issue by MustaphaOuchen** [devonfw/IDEasy#212]
As a developer, I want maven not  to override $MAVEN_OPTS  ( -Duser.home property). So that if I use mvn command to test the application, the correct Java 'user.home' property will be used.

- Check if we can use mvn --settings instead

**Comment by hohwille** [comment]
IMHO we should go away from the `user.home` hack.
The simplest solution I can see is to use `MAVEN_ARGS` instead of `MAVEN_OPTS` what allows us to specify the `-s path/to/settings.xml` option. Can be solved in `IdeVariables` by adding `MAVEN_ARGS` and making it exported.
