### ISSUE TITLE
Alter WireMock tests to use dynamic ports.

### ISSUE THREAD

**Issue by MustaphaOuchen** [devonfw/IDEasy#223]
Currently, the ports are hardcoded. Use dynamic ports. For this, the url files in _ide/urls/... must be created during the test runtime using the assigned dynamic port.

Tests which currently use wiremock:

**cli/src/test/java/com/devonfw/tools/ide/tool/jmc/JmcTest.java

cli/src/test/java/com/devonfw/tools/ide/commandlet/InstallCommandletTest.java**

**Comment by MustaphaOuchen** [comment]
Makes [#193](https://github.com/devonfw/IDEasy/issues/193) obsolete

**Comment by hohwille** [comment]
We have created a new test-infrastructure with PR #238 what makes wiremock obsolete for common tests of commandlets.
So we only need wiremock for the following aspects:
* Testing UrlUpdaters
* Testing our download capabilities including our progress bar and also custom tool repositories
* Potentially for testing downloads of plugins (IntelliJ, Maven)

For those tests we need to ensure there are no conflicts with wiremock ports. As long as this is the case, we should be safe and stable (at least unless new requirements for using wiremock show up).
