### ISSUE TITLE
Cannot update plugins in Eclipse via "check for updates"

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#224]
### Expected behavior

As a IDEasy and eclipse user, I want to be able to get updates so that I benefit from new features and bug+security fixes.

### Actual behavior

Updates are found but cannot be installed
![image](https://github.com/devonfw/IDEasy/assets/1923119/b7fd0103-7f46-441a-9eb2-f529499684c4)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. open an existing eclipse (or install an outdated eclipse version)
2. select `help > check for updates`

### Related/Dependent Issues

I assume this may be related to https://github.com/devonfw/ide/issues/1147
However, it may also be related to symlinks/junctions.

### Affected version:

* current IDEasy
* devonfw-ide 2024.01.001

**Comment by VinceHeu** [comment]
According to inital findings, symlinks/functions have nothing to do with the behavior described. If you don't use the argument "-configuration" with the configuration path (tool=>eclipse=>runEclipse(..)) check for updates is working. Therefore, the assumption is that it has something to do with the configuration. The configuration path currently points to the location where the plugins are installed, but if you use the initial path of the configuration, it does not work either.

**Comment by hohwille** [comment]
I cannot reproduce this bug anymore. Both @ndemirca and I have just checked for updates, got an update of `JustJ` and could successfully install it. So the user is not blocked from this feature. Still it is kind of questionable to do this since we manage software tool products in a stoftware repository in IDEasy. If you install both Eclipse `2024-03` and `2024-06` and then continuously use `2024-03` and check for updates and install all updates you get then over time your `2024-03` installation may be updated and more recent than the `2024-06` version. Since the user has to actively use this "check for updates" feature, he is also in charge for this impact, and I do not see this as a bug of IDEasy.
At least if you have many differen IDEasy projects in parallel on the same computer and they or some of them share the same Eclipse release version, then you need to be aware that these projects are not isolated by [sandbox-priciple](https://github.com/devonfw/IDEasy/blob/main/documentation/sandbox.adoc).

So unless somebody is ever able to reproduce this bug, I will close it as invalid. Feel free to reopen with more details how to reproduce whenever you run into this problem.
