### ISSUE TITLE
When using CMD to use IDEasy the output of the commandlet is not shown

### ISSUE THREAD

**Issue by MustaphaOuchen** [devonfw/IDEasy#234]
### Expected behavior

As a user, I want to see the output when CMD is used.

### Actual behavior

The output is not printed in the cmd console. but it can be still be redirected to a file or with the more command.

### Steps to reproduce 

You need a branch with the state of https://github.com/devonfw/IDEasy/issues/9

First lets try to reproduce expected behavior, which works when using bash.

With IDEasy

1.  Navigate to the cli directory of the project using (devon) bash
2. Run: mvn clean install in the root of the project
3.  Run: devon mvn exec:java -Dexec.mainClass=com.devonfw.tools.ide.cli.Ideasy -Dexec.args=jmc

![Image](https://github.com/devonfw/IDEasy/assets/98693422/e93bf0c5-a2b6-47eb-8ff7-665e5da5433b)

With simple bash:
bash -c /d/projects/IDEasy/software/jmc/jmc.exe & diswon

![Image](https://github.com/devonfw/IDEasy/assets/98693422/1b656845-9054-431a-b636-d857111fcc1d)

Doing the steps above with cmd (replace bash with the location of bash.exe, use "", see screenshot) we do not get any output.

![Image](https://github.com/devonfw/IDEasy/assets/98693422/d6ae318d-c890-4030-b59d-ffa873981492)

![Image](https://github.com/devonfw/IDEasy/assets/98693422/6109903c-376d-4566-a182-515d7bd15e6e)

But, the output of the cmd will be shown when you use the 'more' command or you can still redirect it with '>' to a file.

![Image](https://github.com/devonfw/IDEasy/assets/98693422/ba1d99de-df88-4579-9b62-85becfd2d502)

### Related/Dependent Issues

https://github.com/devonfw/IDEasy/issues/9

### Affected version:
* OS: Windows

**Comment by hohwille** [comment]
I am not quite sure but to me it looks this is not a bug of IDEasy but a problem of MS DOS aka CMD Shell.
In the latter case we can only try to search the web for a workaround but if we find none there is nothing we can do about it.

However, what we also should do is educate developers to use bash. This is a Windows specific issue but as we need git for windows installed every developer has a git-bash as prerequisite and therefore developers should stop using crappy old CMD and just get used to bash.
