### ISSUE TITLE
IDEasy not installing latest version for version pattern

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#235]
From `settings/devon.properties` I have configured the latest Java 17
```
JAVA_VERSION=17*
# ...
```

Now, I want to update the latest version of Java 17:

```
$ ./ideasy.exe install java
Version 17.0.6_10 of tool java is already installed
```

This is incorrect and as you can see the completion is able to suggest the latest stable 17.* version:
![image](https://github.com/devonfw/IDEasy/assets/1923119/597170b5-f483-4ee6-8de8-128d364f8bd4)

**Comment by salimbouch** [comment]
I debugged and the resolved version is actually `17.0.10_7` when installed is `17.0.6_10` and java is set to `17*` in `settings/ide.properties` . Here in [UrlMetadata](https://github.com/devonfw/IDEasy/blob/eb29ec8178d985f96553961370d9b8642b264568/cli/src/main/java/com/devonfw/tools/ide/url/model/UrlMetadata.java#L113) we get a descending sorted list of versions of java and it matches once `17.0.10_7` is reached.

**Comment by hohwille** [comment]
I have retested this issue and it still occurs with our release and latest codebase:
```
$ ideasy install java
Version 17.0.6_10 of tool java is already installed
```
with
```
JAVA_VERSION=17*
```

**Comment by salimbouch** [comment]
With 
```java
JAVA_VERSION=17*
``` 
in `ide.properties` and the installed java version is `17.0.6_10` I get the following behavior: 

```shell
> ./ideasy install java
Start: Install java
Already up to date.

Successfully installed java in version 17.0.11_9 replacing previous version 17.0.6_10
Successfully completed ide (install,java)
``` 
Let's meet and discuss this to see why the `ideasy` release with the latest codebase behaves differently on our machines.

**Comment by hohwille** [comment]
as promised, I retested this again and it gets even more crazy:
```
hohwille@CE49454 MSYS /d/projects/IDEasy
$ ide
IDE environment variables have been set for D:/projects/IDEasy in workspace main

hohwille@CE49454 MSYS /d/projects/IDEasy
$ echo $JAVA_VERSION
17*

hohwille@CE49454 MSYS /d/projects/IDEasy
$ ide install java
Start: Install java
Already up to date.
Version 21_35 of tool java is already installed
Install java
Successfully completed ide (install,java)
```

**Comment by hohwille** [comment]
It does not behave differently. You need to read carefully what my setup is to cause the problem. I will give detailed instructions:
1. Setup project with devonfw-ide
2. Ensure Java version is set to 21 (in `settings/devon.properties` you have `JAVA_VERSION=21*`)
3. Copy your `settings/devon.properties` to `settings/ide.properties`
4. Edit `settings/ide.properties` and change `JAVA_VERSION=17*`
5. Run `ide install java`

**Comment by hohwille** [comment]
Besides our `VersionIdentifier` comparison logic is really incorrect for Java.
I verified this by adding this method to `VersionIdentifierTest` and it is 100% reproducible already at this low level:
```
  @Test
  public void testCompareJavaVersions() {

    VersionIdentifier v21_35 = VersionIdentifier.of("21_35");
    VersionIdentifier v21_0_2_13 = VersionIdentifier.of("21.0.2_13");
    VersionIdentifier v21_0_3_9 = VersionIdentifier.of("21.0.3_9");
    assertThat(v21_35).isLessThan(v21_0_2_13);
    assertThat(v21_0_2_13).isLessThan(v21_0_3_9);
    assertThat(v21_0_3_9).isGreaterThan(v21_35);
  }
```

The test fails with this error:
```
java.lang.AssertionError: 
Expecting actual:
  21_35
to be less than:
  21.0.2_13 
```

Rationale:
https://adoptium.net/download/
The latest release is currently `21.0.3_9` and `21_35` is an old release.
So is bug #1367 not really fixed?
