### ISSUE TITLE
ide wrapper script ends terminal on error

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#260]
### Expected behavior

As a IDEasy user, I want to use `ide` command seamless like `devon` so that I can switch from devonfw-ide to IDEasy.

### Actual behavior

In order to change environment variables the `ide` wrapper script has to be sourced as otherwise it is called as a sub-process with its own inherited environment variables and on exit you return to the parent process what is the users shell (e.g. `git-bash`) and the environment variable changes are lost and have no effect. (see #63):
```
echo 'alias ide="source $(which ide)"' > ~/.bashrc
```
Now, I caused a bug when I tried to simplify the error handling in PR #221 when I decided to use `set -e`.
This is causing to exit the process as soon as an error happens what seemed to make sense at the first glance.
However, now that the `ide` script is sourced, we need to understand that process is our shell (e.g. `git-bash`) and the sourcing behaves as if the code is pasted into my terminal.
So as a result now on any error the process - what is the shell itself - exits.
Therefore, if you are not inside a devonfw-ide/IDEasy project, you will get the message `You are not inside an IDE installation: D:\projects` and an error (exit code not `0`) what will exit your shell.
Or to make it even more obvious:
Using `set -e` in the shell itself is a no-go as any non successful command (`grep 'nonexistent-word' file` or `[ 0 = 1 ]`) will exit your shell.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. install IDEasy
2. add the alias to your `.bashrc` (see above)
3. open a shell in a non devonfw-ide/IDEasy project (e.g. `C:\Windows`)
4. call `ide`

Your shell exits and your terminal closes (or your tab if you are using Windows-Terminal and have other tabs open).

### Related/Dependent Issues

* #63 
* #5 

### Comments/Hints:

We have to reintroduce the error handling (with `return_code=$?`).
Now that we have working SNAPSHOT releases and the major blockers resolved, it is very easy to locally modify the `ide` wrapper script and do a lot of testing of all the variants in order to create a PR fixing the problem.

### Affected version:

* OS: any
* Shell: Bash (but also zsh or other GNU shells)

**Comment by mvomiero** [comment]
## Adding an alias for ide:
⚠️ please note that this line of code doesen't work because of three reasons:
```bash
echo 'alias ide="source $(which ide)"' > ~/.bashrc
```
1. the ` ' ` prevent the interpretation of the variable `$(which ide)`
2. the output should be appended,` >>` instead of `>`, otherwise the content of `.bashrc` would be overwritten and important aliases like `devon `will be lost
3. an alias for ideasy (executed and not sourced) is needed for the wrapper script.

A solution can be saving and executing this bash script in the folder where the new release is downloaded, or execute the lines of code one by one. 

```bash
#!/usr/bin/env bash 

cd bin 
export PATH=$PWD:$PATH 
echo "alias ide=\"source $(which ide)\"" >> ~/.bashrc # alias to source ide 
echo "alias ideasy=\"$(which ideasy)\"" >> ~/.bashrc # alias to execute ideasy 
```
_Terminal has to be closed and reopened after executing the script to make the changes effective_

**Comment by hohwille** [comment]
> ```shell
> echo 'alias ide="source $(which ide)"' > ~/.bashrc
> ```
> 
>     1. the `'` prevent the interpretation of the variable `$(which ide)`

The variable will be resolved when the alias is evaluated.

>     2. the output should be appended,` >>` instead of `>`, otherwise the content of `.bashrc` would be overwritten and important aliases like `devon `will be lost

OMG. Yes, very true. Sorry, my mistake.

>     3. an alias for ideasy (executed and not sourced) is needed for the wrapper script.

You do not need an alias for that but `ideasy` needs to be on the `PATH` variable.
But I simply just changed the wrapper script to call `ideasy` next to the wrapper script so it does not have to be on the `PATH`.
This also solves undesired autocompletion conflicts of `ide` vs. `ideasy`.
