### ISSUE TITLE
end EOL diff-war

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#261]
As a reviewer, I want the diffs to be readable so that I can quickly see what really changed by a commit.

However, something is wrong with out setup (e.g. gitconfig) causing phantom diffs where blocks of lines get removed and then added again with the exact same content. See this example:
https://github.com/devonfw/IDEasy/pull/259/files#diff-e474d2fd29a82638cd39a39f49807ce120fcc4475b4290f613f48ee7fadeb074

I have not yet fully analyzed the problem but it seems that the EOL changed from CRLF to LF or vice versa.
We should not track such changes except for special script files like `ide` (must be LF), `*.bat` such as `ide.bat` (must be CRLF) via `.gitattributes` but e.g. for Java source code the EOL style does not matter. The local EOL style should be ignored or it should always be LF.

We have examples where IntelliJ reformatted a file with no change but we get the full diff with all lines removed and later added as we can see in this example:
https://github.com/devonfw/IDEasy/pull/216/files#diff-cb2a98b8728e5f068b8f381d2ae5da3a31bc035f68878509c5227a185dbccdfb

**Comment by VinceHeu** [comment]
![HideWhitespaces](https://github.com/devonfw/IDEasy/assets/158555544/0d276dad-2ea6-48f2-af80-c0a6edaa9d34)
It's possible to see the differences when choosing the checkbox "hide whitespaces". This is not the solution, but first a suggestion on how to deal with the problem before a solution is found.
