### ISSUE TITLE
Release workflow failing due to permission-related issue

### ISSUE THREAD

**Issue by ndemirca** [devonfw/IDEasy#262]
The following error message appears while creating a new release: 

remote: Permission to devonfw/IDEasy.git denied to hohwille.
fatal: unable to access 'https://github.com/devonfw/IDEasy/': The requested URL returned error: 403
Error: Process completed with exit code 128.

It seems to be a permission related issue.

**Comment by hohwille** [comment]
So here is where the workflow fails:
https://github.com/devonfw/IDEasy/blob/f49f74a1bf9066537f29b73b683d4d4e81727db0/.github/workflows/release.yml#L99

Seems to be a similar issue as we had with out UrlUpdater action that was broken after some token expired.

**Comment by hohwille** [comment]
https://github.com/devonfw/IDEasy/actions/runs/8388379203/job/22972657620

**Comment by hohwille** [comment]
I created a new access token that also has write permissions to IDEasy repo and still also to ide and ide-urls and replaced it in the secrets as `Action_Push_Token`. Fingers crossed that now all actions work without permission denied errors.

**Comment by hohwille** [comment]
Horray, worked. Release is out with green workflow and tags and release arrived on github:
https://github.com/devonfw/IDEasy/releases/tag/release%2F2024.04.001-alpha
