### ISSUE TITLE
Mutation testing

### ISSUE THREAD

**Issue by ndemirca** [devonfw/IDEasy#301]
**Mutation testing** is a technique for assessing the quality of tests by creating artificially faulty versions of the source code, known as "mutants". The goal is to determine if your tests can detect these mutants.  It provides an indicate how effective your tests are if they can uncover potential flaws in the code. 

1. Research various tools and frameworks, such as PIT, for conducting mutation testing.
2. Evaluate and determine the most suitable option for our project.
3. Present the findings to the team.
4. Collaboratively decide on the preferred solution.
5. Implement the chosen approach.

**Comment by slskiba** [comment]
[PIT](https://pitest.org/) seems to be the best adopted mutation testing system for java. 

Alternatives to PIT are often developed for academic purposes and no longer actively developed or supported, such as [muJava](http://cs.gmu.edu/offutt/mujava/), [Jester / Simple Jester](http://jester.sourceforge.net/), [Jumble](http://jumble.sourceforge.net/), or [Javalance](http://www.st.cs.uni-saarland.de/mutation/)

[The Major Mutation Framework](https://mutation-testing.org/downloads/) is in active development, with its latest release in May 29, 2024. However it does not yet support maven, and the standalone usage might be very tricky to implement.
