### ISSUE TITLE
Process stays hanging after installing Docker

### ISSUE THREAD

**Issue by salimbouch** [devonfw/IDEasy#315]
### Expected behavior

As a user of IDEasy, I want to be able to install global tools (like docker) and get a response that it was installed successfully when it's done.

### Actual behavior

The global tool (like docker) is installed, but the process stays hanging and the user can't tell whether the tool was installed successfully or not.

### Steps to reproduce (bug) 

1. ide install docker
 (tested with rancher desktop)

### Comments/Hints:

when debugging the process stays hanging in `run()` in [GlobalToolCommandlet](https://github.com/devonfw/IDEasy/blob/d16b3828562cae2550783b61150363fea375761e/cli/src/main/java/com/devonfw/tools/ide/tool/GlobalToolCommandlet.java#L134C17-L134C29)

### Affected version:
tested on Windows

**Comment by alfeilex** [comment]
Right now the installation of `Rancher Desktop` needs user interactions for installation. After the installation, the process of `msiexec` not terminated properly and the ide process hangs, because it's waiting.
