### ISSUE TITLE
Paths not formatted correctly when running ide env --bash

### ISSUE THREAD

**Issue by aBega2000** [devonfw/IDEasy#321]
### Expected behavior

As a user, I want the Paths to be in Linux syntax when I run "ide env --bash" in terminal

### Actual behavior
 Some Paths are correctly set to Linux syntax, but there are others who are still in Windows syntax, namely "export MAVEN_ARGS" and "WORKSPACE_PATH"

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  Open git bash terminal
2.  Run ide env --bash

![image](https://github.com/devonfw/IDEasy/assets/145266540/98a0f08e-4e27-45bf-ba1c-96154d6c0f4c)

**Comment by slskiba** [comment]
Furthermore, there is also a mismatch in forward/backward slash usage in `env --bash` (as seen above), but also in `env`: 

```
ide> env
export PATH="C:\projects\IDEasy\   [...]"
[...]
HOME="C:/Users/sskiba"
```
