### ISSUE TITLE
Inconsistent npm version

### ISSUE THREAD

**Issue by ndemirca** [devonfw/IDEasy#324]
The command 'npm get-version' retrieves the npm version, while 'npm -v' displays the version of npm bundled with node.

![image](https://github.com/devonfw/IDEasy/assets/157051033/8fb87a85-4b8e-4d92-a2f6-f0c1e2612b53)
  
See also #352

**Comment by tobka777** [comment]
Expected State should be `npm -v`

**Comment by hohwille** [comment]
See #352 what is very relevant in this regard. Most probably we can close this issue as kind of "duplicate".

**Comment by hohwille** [comment]
The term "duplicate" may be questionable here but if #352 is fully implemented, then this bug issue is resolved. Hence, I am closing it now.
