### ISSUE TITLE
Uninstall multiple tools at the same time

### ISSUE THREAD

**Issue by ndemirca** [devonfw/IDEasy#326]
Enhance the UninstallCommandlet implementation to support uninstalling multiple tools at the same time.

**Comment by hohwille** [comment]
Another though on this is being symmetric:
If I can do `ide uninstall tool1 tool2 tool3` why cant I then also do `ide install tool1 tool2 tool3`.
What is to be considered is that we can also do `ide install tool1 1.0.0` where `1.0.0` is not a tool but a version number.
Therefore I am not yet voting to do this but just thinking loud...
