### ISSUE TITLE
CLI misinterpretation of the first tool argument as combined short options - e.g. ide java -version

### ISSUE THREAD

**Issue by mvomiero** [devonfw/IDEasy#330]
### Actual behavior

* if the first argument of a tool starts with "-", then `CliArgs` wrongly interprets it as combined short options. E.g. `-version` is interpreted as `-v -e -r -s -i -o -n`

### Steps to reproduce
For example in java, but it's the same for other tools as well (like mvn):

<img width="578" alt="ide_version" src="https://github.com/devonfw/IDEasy/assets/102261609/6668097a-7a0b-49fa-8c2f-3b3c5cf5c99b">

* Note: the bug is just for `ide java -version`, all the other cases work fine:
  * `ide java --version`
  * ` java -version`
  * ` java -- -version`

**Comment by slskiba** [comment]
Might be a feature, and not a bug, considering the following design choice: 
https://github.com/devonfw/IDEasy/blob/5a5c2abf0702cb5fbdbc14d7a2be36fe8eb00529/cli/src/main/java/com/devonfw/tools/ide/cli/CliArgument.java#L174

**Comment by jan-vcapgemini** [comment]
Seems to be a bug because running this: `ide mvn package -DskipTests` lead to:
Running command 'D:\Projects\ideasy-dev\software\mvn\bin\mvn.cmd' with arguments 'package' '-D' '-s' '-k' '-i' '-p' '-T' '-e' '-s' '-t' '-s' failed with exit code 1!

**Comment by hohwille** [comment]
@jan-vcapgemini Let me take over this issue and try to create a test and fix for it.

**Comment by jan-vcapgemini** [comment]
I've not managed to reproduce this issue with a test yet. Possible solution could be in `AbstracIdeContext/apply`. 
```
if (property.isMultiValued()) {
  trace("Property is multivalued, prevent short options");
  arguments.endOptions();
}
```
