### ISSUE TITLE
IDEasy Mac intel architecture support for native image builds

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#337]
We need MacOs intel support for our build pipeline as we currently use mac-latest which appears to be the ARM architecture.
@tobka777 already found a fitting os tag: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners e.g. `macos-13`

**Comment by hohwille** [comment]
As PR #365 did not fix this issue, I will reopen.
Things to consider:
* https://github.com/devonfw/IDEasy/blob/e2ab777405570d8968785571f06688a1336f7acc/cli/pom.xml#L155-L169
* https://github.com/devonfw/IDEasy/blob/e2ab777405570d8968785571f06688a1336f7acc/cli/pom.xml#L290
* https://github.com/devonfw/IDEasy/blob/998ef92c86551576eaca1fc8e2f005a67fb8c18d/.github/workflows/release.yml#L13

so we have to add the architecture also to the classifier and add a fourth release to our pom, etc.
