### ISSUE TITLE
ide shell: autocompletion of version not working propertly

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#357]
Working as expected
```
$ide shell
ide> install eclipse 20[tab]
2024-03   2023-12   2023-06   2022-12   2022-06   2021-12   2021-06   2020-12   2020-06   2019-12
20*       2023-09   2023-03   2022-09   2022-03   2021-09   2021-03   2020-09   2020-03   20*!
```

Not working as expected:
```
$ide shell
ide> install eclipse 2024[tab]
2024*    2024*!
```

**Comment by slskiba** [comment]
> Working as expected
> 
> ```
> $ide shell
> ide> install eclipse 20[tab]
> 2024-03   2023-12   2023-06   2022-12   2022-06   2021-12   2021-06   2020-12   2020-06   2019-12
> 20*       2023-09   2023-03   2022-09   2022-03   2021-09   2021-03   2020-09   2020-03   20*!
> ```

This is is fact not working as expected, as version 2019-09 is missing.
