### ISSUE TITLE
Integrate ToolCommand with UrlUpdater

### ISSUE THREAD

**Issue by alfeilex** [devonfw/IDEasy#40]
After https://github.com/devonfw/ide/issues/1194 is implemented, we want to archive that we can implement one "tool" in one class with as little effort and code as necessary. My vision is that we will just have once class for each tool called `Mvn, Java, Eclipse,` etc. that both contains the commandlet logic as well as the logic for the UrlUpdater.
In case this does not work out well with inheritance (different UrlUpdater base-classes and `ToolCommand` base-class that later might also get further abstract sub-classes), we could have a method `public abstract UrlUpdater getUpdater()` in `ToolCommand`. In our classes like `Java, Eclipse`, etc. we can have the `UrlUpdater` implementation as inner class and return its singleton instance via `getUpdater().`

Issue was transferred from: https://github.com/devonfw/ide/issues/1195

**Comment by hohwille** [comment]
We have discussed this in a team meeting. With this design we couple the UrlUpdater tightly with the ToolCommandlet. While this may have some pros (e.g. if you implement a new ToolCommandlet you would be forced to provide an UrlUpdater and therefore cannot forget to think about it) it has several cons:
* we sometimes have multiple UrlUpdaters for the same tool/commandlet - e.g. one per edition. This would make the design more complex.
* we sometimes had temporary problems with a particular UrlUpdater and disabled it. Having a separate place where to register (and enable/disable) all UrlUpdaters therefore still makes sense.

The team has convinced me that my initial idea is not so good.
What I have already done is to move the concrete UrlUpdaters into the `tool` package. Therefore we now have everything for one particular tool (e.g. `java`) in one package (e.g. `....tool.java`) that is the commandlet, the UrlUpdater and potential JSON objects.
I will therefore close this issue as wontfix.
