### ISSUE TITLE
Inconsistent behavior of get-version and get-edition

### ISSUE THREAD

**Issue by slskiba** [devonfw/IDEasy#410]
### Actual behavior
Inconsistent behaviour:
`get-edition` of a local tool that is not installed provides the configured edition and instructions on how to install the tool, however
`get-version` of a local tool that is not installed results in a `CliException: Tool <tool> is not installed`
`get-version` of a global tool fails in  `CliException: Tool <tool> is not installed`: Tool not installed, whether it is installed or not. 

### Related Issues
#399

### Comments/Hints:
The current implementation for get-version and get-edition is only applicable to local tools.

**Comment by hohwille** [comment]
I get different results:
```
$ ide -v
2024.06.001-alpha-SNAPSHOT
Successfully completed ide (-v)
$ ide get-version aws
2.15.58
Successfully completed ide (get-version,aws)
```

Can you specify how to reproduce the `CliException: Tool is not installed` case?

**Comment by hohwille** [comment]
However, some things are inconsistent:
```
$ ide get-edition docker
The configured edition for tool docker is rancher
To install that edition call the following command:
ide install docker
Successfully completed ide (get-edition,docker)
```

I also was now able to reproduce the reported error:
```
$ ide get-version helm
Step 'ide (get-version,helm)' failed: com.devonfw.tools.ide.cli.CliException: Tool helm is not installed!
1 step(s) failed out of 1 steps.
Tool helm is not installed!

Error: IDEasy failed with exit code 4
```

**Comment by slskiba** [comment]
Seems like aws is installed in your case. The exception of course occurs when a tool is not installed.
However get-edition does not throw this exception when a tool is not installed - I suggest they should behave similar when called on a tool that is not installed.
