### ISSUE TITLE
Nightly build successful even if previous action failed because of the verify_commit job

### ISSUE THREAD

**Issue by mvomiero** [devonfw/IDEasy#426]
### Expected behavior

Nightly build should fail if the last workflow that executed all the jobs (not only `verify_commit`) failed.

### Actual behavior

If there is no commit in the last 24 hours, the workflow will just execute the `verify_commit` job and will succeed even if the last workflow run was failing.

### Related/Dependent Issues

#361 
#406

**Comment by hohwille** [comment]
My suggestion is to finally go to the proposed KISS approach and just always do the build every night to make it work.
When this is live, we can again start work on a more sustainable build workflow and once it is completed and carefully tested, we can go back to a smarter approach.
