### ISSUE TITLE
IntelliJ settings not working for 2024.* versions

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#464]
### Expected behavior

As a IntelliJ user, I want IDEasy to preconfigure my IntelliJ settings automatically so that I can start coding instantly. This also includes pre-configuring the code-style with indent, line-wrapping, etc.

### Actual behavior

With IntelliJ 2024.* versions this stopped working. It seems that the internal configuration has changed from where IntelliJ reads the code-formatter settings on the disc.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. `ide create ij-test-project`
2. `cd $IDE_ROOT/ij-test-project`
3. `ide intellij`
4. open settings and check formatter (start-imports should be 999, indent should be 2, etc. but all wrong)

### Related/Dependent Issues

#52 

### Comments/Hints:

We first need to analyze where the new IntelliJ is now writing the config to and in which format.
In the worst case they have changed this entirely and we need to configure both the old and the new config file in our `ide-settings` to make it work with any IntelliJ version.

### Affected version:

* OS: tested on Windows but most likely any OS
* Intellij: 2024.*, tested with 2024.1.4

**Comment by jan-vcapgemini** [comment]
With the latest changes of #478 and https://github.com/devonfw/IDEasy/issues/464 this issue seems to be solved as the latest (2024* ) intellij is successfully starting up and loading all settings properly.

**Comment by jan-vcapgemini** [comment]
Closing issue.
