### ISSUE TITLE
Use plant UML for class diagram

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#544]
For internal development we created a high-level design class diagram so new developers can get an overview to get started.
This was created with DrawIO as [Design.drawio](https://github.com/devonfw/IDEasy/blob/main/documentation/images/Design.drawio) and then exported as [Design.png](https://github.com/devonfw/IDEasy/blob/main/documentation/images/Design.png).

The diagram should be updated. Therefore we need to pull the latest drawio file, edit it with DrawIO desktop app, save changes, export as PNG and overwrite the PNG. Then push all these binary changes to git.

An alternative is to use [plant UML](https://plantuml.com/) that is a markup language for UML and other diagrams as wiki text.
This has many advantages and even allows to understand the diff of changes in git.
The only disadvantage is that it can get quite cumbersome to make the layout of a complex diagram nice since you cannot move boxes/items around like in DrawIO.
There is also an [IntelliJ Plantuml plugin](https://plugins.jetbrains.com/plugin/7017-plantuml-integration) that shows a live-preview of your `puml` file while editing.
You can even `include` a `puml` from `adoc` to embed it as an image and asciidoctor can render it into the PDF or website.

Therefore this story is about the following changes:
* [x] Create a new `Design.puml` file in our `documentation` showing the contents of our current `Design.png`
* [x] Extend the `Design.puml` to reflect the latest changes (add `IdeLoggerImpl`, `GitContext`, `LocalToolCommandlet`, `GlobalToolCommandlet`)
* [x] Remove the old `Design.png` and `Design.drawio` files
* [x] Remove/update links to the old files and instead include puml to dev getting started.

Extracted separate issue #579 for last remaining point so we can close this issue for the release.

**Comment by slskiba** [comment]
To not break the installation of intellij by failing plugin installations, the first point (add the plugin file with plugin_active=true to ide-settings) first requires the following issue to be solved:
- #550

**Comment by hohwille** [comment]
Reopening until first task is completed.
