### ISSUE TITLE
Implement auto-completion

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#56]
As a IDEasy user, I want to have command-line auto-completion so that I can be more productive and do not always have to read the help pages.

We had implemented this in devonfw-ide with manually bash scripts and the bash completion infrastructure.
My vision is that we pass the arguments to auto-complete directly into our Java main program.
So more or less `Ide complete «args»` would be called and we solve this with a `CompleteCommandlet`.
By finding the proper commandlet to invoke we can find its arguments and depending on their type automatically determine the possible options. That is why I prepared according specific `Property` sub-classes so that for a `VersionProperty` we know that a version-number is to be passed and from out tool-commandlet to be invoked, we can figure out the possible and matching versions.

BTW: This story is not easy and therefore not good for beginners. Also I learned that debugging auto-completion while using it is tricky as you can not use debug output to the console while pressing [Tab] key. It is therefore good to have an understanding of how auto-completion in bash works and then first have JUnits covering the different cases (completion of a single word where a prefix of that word is already given vs. a new word is started, etc.). If still some debugging is needed it is better to temporary write a log-file with the input and output of the auto-completion to later understand what went wrong and why... Good luck with this story :)

**Comment by jan-vcapgemini** [comment]
@MattesMrzik found out that there seems to be an issue with the WIndows Terminal on Windows 11.
The jline3 autocompletion does not work at all on Windows 11. Currently if you hit tab, the terminal just adds a tabstop character to the prompt.
