### ISSUE TITLE
mismatch of working directory

### ISSUE THREAD

**Issue by ndemirca** [devonfw/IDEasy#574]
### Actual behavior

IDEasy incorrectly assumes that the current working directory would be `D:\projects\_ide\software\default\java\java\21.0.4_7` while it is actually  `/d/projects/IDEasy/software/java`.

![image](https://github.com/user-attachments/assets/83b7b27c-5fe3-4272-9968-235d49266ded)

### Steps to reproduce (bug) 

1.  execute $ ide help in /d/projects/IDEasy/software/java

**Comment by hohwille** [comment]
FYI: The folder `/d/projects/IDEasy/software/java` is a Junction (Windows specific variant of a kind of symbolic link) to `/d/projects/_ide/software/default/java/java/21.0.4_7`.
Still the behavior is not expected and considered as bug.
Maybe we are doing a `Path.toRealPath()` somewhere on our working directory that would explain the problem.
It could be that already `Path.toAbsolutePath()` is causing this effect and then we would have to implement a specific workaround.
