### ISSUE TITLE
NoSuchFileException for FETCH_HEAD of settings

### ISSUE THREAD

**Issue by ndemirca** [devonfw/IDEasy#585]
### Actual behavior
![image](https://github.com/user-attachments/assets/44034406-a90f-46b4-9da0-28b443b31be3)

Bug is caused by PR https://github.com/devonfw/IDEasy/pull/467, a check should be added to see if the file exists.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Use the 2024.09.001-beta-SNAPSHOT/
2. execute ide intellij

**Comment by hohwille** [comment]
Bug is here:
https://github.com/devonfw/IDEasy/blob/b70c7708d30988c016c99c32da38a3d648b55384/cli/src/main/java/com/devonfw/tools/ide/context/GitContextImpl.java#L108

**Comment by hohwille** [comment]
See also here:
https://stackoverflow.com/questions/9237348/what-does-fetch-head-in-git-mean

**Comment by hohwille** [comment]
```
$ cd settings
$ cat .git/FETCH_HEAD
8f6da8c195e2932976374913dd34ecdd344614df                branch 'main' of https://github.com/devonfw/ide-settings
```

**Comment by hohwille** [comment]
```
hohwille@CE49454 MSYS /d/projects/_ide/urls/.git (GIT_DIR!)
$ cat FETCH_HEAD
113385c2d89fce8c8306ef3c26b6642d9ee38be6                branch 'master' of https://github.com/devonfw/ide-urls
```
