### ISSUE TITLE
Documentation has AsciiDoc syntax errors

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#590]
Our build logs are spammed since many month with warnings and especially the entire source code of the `LICENSE.adoc` that got a syntax error by some PR adding to the documentation.

These are the errors from asciidoctor:
```
[INFO] asciidoctor: ERROR: projects.adoc: line 51: table missing leading separator; recovering automatically
[INFO] asciidoctor: WARN: LICENSE.adoc: line 84: unterminated table block
[INFO] asciidoctor: ERROR: LICENSE.adoc: line 86: table missing leading separator; recovering automatically
[INFO] asciidoctor: ERROR: failed to parse formatted text: <a name="license.adoc_apache-software-license---version-2.0"></a> == Apache
```

Initial task of this story is to analyze and fix these errors.

If possible we should configure asciidoctor to fail on errors. Then the PR introducing the error would get a red build and we would not merge it before the error gets fixed.

**Comment by alfeilex** [comment]
Derived issue for [`doc-gen`](https://github.com/devonfw/docgen/issues/36) to configure that the build process fails when there are errors in `adoc` files
