### ISSUE TITLE
Enhance error messsages of ProcessBuilder

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#608]
As an IDEasy user, I want to see what exactly failed when an application was not run successfully.

Currently IDEasy only shows the exit code of a failed process and omits the error messages in the log.

See: https://github.com/devonfw/IDEasy/blob/e73c7ae38f397c01fd8131bd62d0323b72b5a3d5/cli/src/main/java/com/devonfw/tools/ide/process/ProcessContextImpl.java#L284-L287

We could easily add `result.getErr()` here too.

UPDATE (JH): This should depend on `ProcessMode` so e.g. for `DEFAULT` all output was already redirected to the shell. However, for `DEFAULT_CAPTURE` we should output what has been captured (IMHO both stdout and stderr).
Somehow this is a duplicate or at least strongly overlaps with #593.

**Comment by hohwille** [comment]
What is the status here?
According to #593 most of this issue is already implemented.

**Comment by hohwille** [comment]
IMHO #593 problem went away since output is not captured anymore.
But in case of capture this story still needs to be implemented.
