### ISSUE TITLE
IDEasy labeler not working correctly

### ISSUE THREAD

**Issue by moritzLanger** [devonfw/IDEasy#61]
### Expected behavior

As a IDEasy developer, I want the github-action bot to correctly label Issues and PR.

### Actual behavior

Currently every PR is labeled as bash, despite not being Bash.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  create PR and it will automatically be labeled as bash

### Comments/Hints:

https://github.com/devonfw/IDEasy/blob/main/.github/labeler.yml

### Affected version:

* Github

**Comment by hohwille** [comment]
Following KISS would be to delete the workflow (label-pr.yml) and its config (labeler.yml).
