### ISSUE TITLE
fix ide-projects to be consisent for tests

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#689]
In PR #665 I introduced an improvement of our test infrastructure by removing some hack.
There I added this log message to spot and highlight inconsistent ide-projects and tests:
https://github.com/devonfw/IDEasy/blob/51a16e1e9e58ef79ed78f4b731b74066fac63ae2/cli/src/test/java/com/devonfw/tools/ide/repo/ToolRepositoryMock.java#L39

If you now run all our tests you will find lots of such exceptions spamming our logs.
We need to get rid of this since it is indicating inconsistent test projects.

In order to fix this all we need to do is create the according tool versions in `urls` of the according project.
The tool versions missing are reported in the exception message.
Examples how to fix this are included in PR #665 and can therefore be found in the diff (Files changed tab).

The job of this story is to complete this cleanup until all such errors are gone.
If that is the case, then please also remove the try catch block from the above linked code point so that in the future no further such inconsistencies can be created.

**Comment by jan-vcapgemini** [comment]
There are still some tests with missing urls.
Please check the latest build log and search for "Invalid test project using version".
We also need to remove the try-catch block when all tests were adjusted.
