### ISSUE TITLE
IDEasy not working properly in CMD

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#764]
### Expected behavior

As a IDEasy user on Windows, I want to be able to use IDEasy also in CMD so that I can use it from some `*.bat` scripts or keep my odd legacy habbits ;)

### Actual behavior

![grafik](https://github.com/user-attachments/assets/523e8adc-6adc-4492-917f-437d159ac130)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install IDEasy
2. Open CMD
3. `cd` to an IDEasy project
4. run e.g. `ide intellij`

### Affected version:

* OS: Windows
* IDEasy 2024.11.001-beta-SNAPSHOT

**Comment by hohwille** [comment]
PR #784 does not fix this problem.
There is something generally broken, when we execute bash scripts in case we have been initially launched from CMD:
```
D:\projects\IDEasy\software\java\bin>ide install intellij
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
Running command 'C:\Program Files\Git\cmd\git.exe' with arguments '--no-pager' 'pull' '--quiet'
failed with exit code 1!
Git pull on branch master failed for repository D:\projects\_ide\urls.
Failed to update git repository at D:\projects\_ide\urls
See above error for details. If you have local changes, please stash or revert and retry.
Typically you should abort and fix the problem. Do you want to continue anyways?
Option 1: yes
Option 2: no
```

Workaround: Do not use CMD at all as suggested in the documentation.
However, we still need to fix this.

**Comment by hohwille** [comment]
Seems to be closely related to https://github.com/devonfw/ide/issues/1395

**Comment by alfeilex** [comment]
There are not problems using CMD to run `ide intellij` on Win 10. 

Tested with version: [ide-cli-2024.12.001-beta-20241210.023937-17-windows-x64.tar.gz](https://s01.oss.sonatype.org/content/repositories/snapshots/com/devonfw/tools/IDEasy/ide-cli/2024.12.001-beta-SNAPSHOT/ide-cli-2024.12.001-beta-20241210.023937-17-windows-x64.tar.gz)

**Comment by alfeilex** [comment]
But if I run `ide create <project>`, I get this error: 

```
Cloning into '.'...
remote: Enumerating objects: 1296, done.
remote: Counting objects: 100% (327/327), done.
remote: Compressing objects: 100% (147/147), done.
Receiving objects: 100% (1296/1296), 236.80 KiB | 2.85 MiB/s, done. 969 (from 1)

Resolving deltas: 100% (501/501), done.
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
Running command 'C:\Program Files\Git\bin\git.exe' with arguments 'clone' '--recursive' 'https://github.com/devonfw/ide-settings.git' '--config' 'core.autocrlf=false' '.'
failed with exit code 1!
Step 'Clone settings repository' ended with failure.
Step 'ide (create,test)' failed: com.devonfw.tools.ide.cli.CliProcessException: Command git.exe failed with exit code 1 - full commandline was C:\Program Files\Git\bin\git.exe clone --recursive https://github.com/devonfw/ide-settings.git --config core.autocrlf=false .
 Step 'Clone settings repository' failed: unexpected error
2 step(s) failed out of 2 steps.
Command git.exe failed with exit code 1 - full commandline was C:\Program Files\Git\bin\git.exe clone --recursive https://github.com/devonfw/ide-settings.git --config core.autocrlf=false .

IDE environment variables have been set for C:\projects\dev-project in workspace main
```

**Comment by alfeilex** [comment]
> D:\projects\IDEasy>set PATH=%PATH%;C:\Program Files\Git\usr\bin


I had to add `C:\Program Files\Git\mingw64\libexec\git-core` as well, because otherwise `git-sh-setup` wasn't found when creating a project.
