### ISSUE TITLE
Intellij does not start

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/IDEasy#766]
### Expected behavior

As an IDEasy intellij user I expect that `intellij` will start properly after running `ide intellij`.

### Actual behavior
Instead of starting intellij I get following error:

![image](https://github.com/user-attachments/assets/5ad3e961-81b7-4c2e-956c-5132d9356464)

`0 [main] bash 475 doFork: died waiting for dll loading, errno`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Run` ide intellij`

### Comments/Hints:
The user was using Intellij Ultimate before and has a regular installation.
Starting intellij (idea64.exe) from the software path directly works without issues.
Starting intellij from the Windows Terminal using git bash works without issues
Starting intellij from git bash through `CMD` with params `-l -i` seems to be the solution?
### Affected version:

* OS: Windows 11 x64
* Intellij community: 2023*, 2024*

**Comment by hohwille** [comment]
IMHO this issue as fixed with PR #784.
Could you try to re-test with the latest SNAPSHOT version?
