### ISSUE TITLE
Improve writing changes to ide.properties

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#78]
In case we are changing the value of a property and saving the changes back to disc, I want to have that the order of the lines in the `ide.properties` file remains stable so that only the new value is changed in the line where the property was declared before.

Assuming we have this `ide.properties` file with some legacy history:
```
#here we define the maven version for both the old and the new release to avoid incompatiblities...
MVN_VERSION=3.9.4
MAVEN_VERSION=${MVN_VERSION}
#here we define to use commercial ultimate edition for Intellij as all team members have a license...
INTELLIJ_EDITION=ultimate
INTELLIJ_EDITION_TYPE=u
```

Now if we run `ide version-set mvn 3.9.5` (see #79) we should get:

```
#here we define the maven version for both the old and the new release to avoid incompatiblities...
MVN_VERSION=3.9.5
MAVEN_VERSION=${MVN_VERSION}
#here we define to use commercial ultimate edition for Intellij as all team members have a license...
INTELLIJ_EDITION=ultimate
INTELLIJ_EDITION_TYPE=u
```

So the following would be undesired:
```
#here we define the maven version for both the old and the new release to avoid incompatiblities...
MAVEN_VERSION=${MVN_VERSION}
#here we define to use commercial ultimate edition for Intellij as all team members have a license...
INTELLIJ_EDITION=ultimate
INTELLIJ_EDITION_TYPE=u
MVN_VERSION=3.9.5
```

Even more wrong would be:
```
#here we define the maven version for both the old and the new release to avoid incompatiblities...
MVN_VERSION=3.9.4
MAVEN_VERSION=${MVN_VERSION}
#here we define to use commercial ultimate edition for Intellij as all team members have a license...
INTELLIJ_EDITION=ultimate
INTELLIJ_EDITION_TYPE=u
MVN_VERSION=3.9.5
```

**Comment by MattesMrzik** [comment]
I have looked at the code and also tried some value changes of properties and saved the changes back to disc. I set some arbitrary helm versions.
`ide set-version helm 1`
then after some additional manual changes the file settings/ide.properties looked like: 
```shell
...
HELM_VERSION=1
a=1
b=2
c=3
``` 
Then I ran `ide set-version helm 1.1` and the file then looked just as desired:
```shell
...
HELM_VERSION=1.1
a=1
b=2
c=3
```

**Comment by MattesMrzik** [comment]
EnvironmentVariablesPropertiesFile.set() can create new properties. It can also set new values for existing ones or change the "export" flag. Possibly a bug: the "export" flag is only updated if the value changes as well.
