### ISSUE TITLE
Implement ToolCommandlet for Kubernetes

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#81]
Create ToolCommandlet for Kubernetes (`kubectl`)
Old commandlet:
https://github.com/devonfw/ide/blob/master/scripts/src/main/resources/scripts/command/kubectl
ATTENTION: Blocked by issue #16 that should be implemented first or together with this story.
NOTE: there is no installation for kubernetes/kubectl itself so we need to override `install(boolean)` and just delegate installation to `Docker` without calling `super.install(silent)`.

**Comment by slskiba** [comment]
Some work done at https://github.com/cwieschnat/IDEasy/tree/feature/81-implement-tool-commandlet-for-kubernetes
