### ISSUE TITLE
MSI file installation fails

### ISSUE THREAD

**Issue by MattesMrzik** [devonfw/IDEasy#87]
### Expected behavior

.msi files corresponding to toolCommandlets should get installed just fine.

### Actual behavior

msi exit code 1639, something is wrong with command line arguments passed to _msiexec_.

### Steps to reproduce 

1.  try to install toolCommandlet that uses .msi files

### Comments:
The command line arguments should use single "/" instead of "//". For example: /a instead of //a

### Affected version:

* OS: Windows

**Comment by hohwille** [comment]
Fixed with PR #88
