### ISSUE TITLE
copy of MSI file is not deleted after installation

### ISSUE THREAD

**Issue by MattesMrzik** [devonfw/IDEasy#89]
### Expected behavior

The copy of the .msi file created by msiexec should get deleted after installation of that .msi file.

### Actual behavior

The copy does not get deleted.

### Steps to reproduce

1.  install a toolCommandlet that uses a .msi file.

### Comments/Hints:

A wrong path is passed to the  fileAccess.delete method in ToolCommandlet.java

### Affected version:

* OS: Windows

**Comment by hohwille** [comment]
Fixed with PR #90
