### ISSUE TITLE
Implement solution for launching background process and emulating start command

### ISSUE THREAD

**Issue by hohwille** [devonfw/IDEasy#9]
In IDEasy we use `ProcessContext` to launch external programs that under the hood uses `ProcessBuilder`.
We need to add support to run a process in "background" such that it runs independent of our IDEasy process (JVM or native-image) so IDEasy CLI can terminate while the launched process will keep running.
This is required e.g. to launch graphical tools such as IDEs (Eclipse, Intellij, VSCode, Android-Studio, GCViewer, JMC, etc.).
Further from bash we are using the windows `start` command to launch some processes like Eclipse to avoid extra CMD windows from opening.
All this has to be solved and implemented in Java and it turns out that such fundamental basics are hard to find as regular searches and even specific tutorials about Process and ProcessBuilder do not say a single word about these aspects.

**Comment by hohwille** [comment]
As it seems running tools in background that do not terminate when the IDEasy CLI process terminates is already working.
However, the `start` command "emulation" issue is still open and waiting for a creative solution.

**Comment by MattesMrzik** [comment]
Under Windows we may use `START /B program` and under Linux `program &`. However, I did not test these.

**Comment by hohwille** [comment]
@MustaphaOuchen found this JDK-Bug:
https://bugs.openjdk.org/browse/JDK-8168608

It seems a very common demand that is lacking in Java. What a pity.
So maybe we need to run indirectly as suggested by @MattesMrzik in the comment above.

**Comment by MustaphaOuchen** [comment]
# Current problem on Windows:

I've tried to use & and START /B. START /B seems  to "throw away" the output stream when starting UI-Applications. You can recreate the scenario with the cli:

## UI-Application problem
1.) navigate to a UI application in cmd/powershell
2.) run (replace program.exe for example with eclipse or jmc): **cmd.exe /c start /b program.exe**
3.) A cmd window opens, but the output will not be printed- you may run **cmd.exe /c start /b program.exe > output.txt** to see expected output.

If you perform the same command with a cli application, you get the expected output and behavior that the program prints its output to the console.

For example, this simple python program saved as test.py can be started with: **cmd.exe /c start /b python test.py**

`import time

def print_hello_every_10_seconds():
    while True:
        print("Hello")
        time.sleep(10)  # sleep for 10 seconds

if __name__ == "__main__":
    print_hello_every_10_seconds()`
